import { Question } from "@/types";

// Test 2 — Romantic Profile Test (25 questions, 5 sections)
export const questions: Question[] = [
  // SECTION A — WHO YOU ARE (Big Five OCEAN)
  {
    id: "q1",
    section: "Кой си ти",
    text: "Обичам да съм в центъра на социалните ситуации.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q2",
    section: "Кой си ти",
    text: "Склонен/а съм да планирам предварително, а не да действам спонтанно.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q3",
    section: "Кой си ти",
    text: "Често поставям нуждите на другите пред моите собствени.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q4",
    section: "Кой си ти",
    text: "Настроението ми е общо взето стабилно и предсказуемо.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q5",
    section: "Кой си ти",
    text: "Любопитен/на съм за хора, много различни от мен.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },

  // SECTION B — HOW YOU LOVE (Love Languages + Sternberg)
  {
    id: "q6",
    section: "Как обичаш",
    text: "Кое от следните те кара да се чувстваш най-обичан/а? (Избери 2)",
    type: "multi",
    selectCount: 2,
    options: [
      { label: "Думи на признателност", value: "words" },
      { label: "Актове на грижа", value: "acts" },
      { label: "Подаръци, малки или големи", value: "gifts" },
      { label: "Качествено съвместно време", value: "time" },
      { label: "Физически допир, прегръдки", value: "touch" },
    ],
  },
  {
    id: "q7",
    section: "Как обичаш",
    text: "Колко важна е физическата близост за теб в дългосрочна връзка?",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Не е важна",
    maxLabel: "Изключително",
  },
  {
    id: "q8",
    section: "Как обичаш",
    text: "Когато съм влюбен/а, го усещам най-силно като...",
    type: "choice",
    options: [
      { label: "Дълбока емоционална връзка и приятелство", value: "intimacy" },
      { label: "Интензивна страст и желание", value: "passion" },
      { label: "Решение и ангажираност", value: "commitment" },
      { label: "И трите поравно", value: "balanced" },
    ],
  },
  {
    id: "q9",
    section: "Как обичаш",
    text: "Вярвам, че страхотната връзка изисква постоянни усилия и внимание.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q10",
    section: "Как обичаш",
    text: "Колко важно е партньорът ти да споделя твоите хобита?",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Не е важно",
    maxLabel: "Много важно",
  },

  // SECTION C — HOW YOU ATTACH (Attachment Theory)
  {
    id: "q11",
    section: "Как се привързваш",
    text: "Когато някой, който ми харесва, не отговори бързо, обикновено...",
    type: "choice",
    options: [
      { label: "Приемам, че са заети, и продължавам", value: "secure" },
      { label: "Чувствам лека тревожност и се чудя защо", value: "anxious" },
      { label: "Дръпвам се, за да се предпазя", value: "avoidant" },
      { label: "Анализирам и препрочитам последния разговор", value: "preoccupied" },
    ],
  },
  {
    id: "q12",
    section: "Как се привързваш",
    text: "Във връзките ми е лесно да разчитам на другите.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q13",
    section: "Как се привързваш",
    text: "Когато възникне конфликт, първият ми инстинкт е...",
    type: "choice",
    options: [
      { label: "Да го обсъдим веднага", value: "direct" },
      { label: "Да взема разстояние преди разговор", value: "space" },
      { label: "Да потърся успокоение от партньора", value: "reassure" },
      { label: "Да го омаловажа и продължа", value: "minimise" },
    ],
  },
  {
    id: "q14",
    section: "Как се привързваш",
    text: "Колко комфортно ми е с уязвимостта: споделяне на страхове, несигурност, провали?",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Никак",
    maxLabel: "Напълно",
  },
  {
    id: "q15",
    section: "Как се привързваш",
    text: "Притеснявам се, че хората, които обичам, в крайна сметка ще ме напуснат.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },

  // SECTION D — WHAT YOU VALUE
  {
    id: "q16",
    section: "Какво цениш",
    text: "Колко важно е партньорът ти да споделя същите религиозни или духовни убеждения?",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Не е важно",
    maxLabel: "Много важно",
  },
  {
    id: "q17",
    section: "Какво цениш",
    text: "Искаш ли деца или още деца?",
    type: "choice",
    options: [
      { label: "Да, определено", value: "yes" },
      { label: "Отворен/а съм за идеята", value: "open" },
      { label: "Не", value: "no" },
      { label: "Вече имам деца, не търся повече", value: "have" },
    ],
  },
  {
    id: "q18",
    section: "Какво цениш",
    text: "Когато си представяш живота си след 10 години, кое е най-съществено?",
    type: "choice",
    options: [
      { label: "Дълбоко, стабилно партньорство", value: "partnership" },
      { label: "Професионални постижения", value: "career" },
      { label: "Семейство и дом", value: "family" },
      { label: "Лична свобода и приключения", value: "freedom" },
    ],
  },
  {
    id: "q19",
    section: "Какво цениш",
    text: "Как обикновено се справяш с несъгласия във връзка?",
    type: "choice",
    options: [
      { label: "Опитвам да намеря компромис бързо", value: "compromise" },
      { label: "Първо слушам, после изразявам мнението си", value: "listen" },
      { label: "Трудно ми е да оставам спокоен/а", value: "reactive" },
      { label: "Склонен/а съм да избягвам трудни разговори", value: "avoid" },
    ],
  },
  {
    id: "q20",
    section: "Какво цениш",
    text: "Финансовите ми ценности и навици трябва да бъдат споделени от партньор.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },

  // SECTION E — SELF-AWARENESS
  {
    id: "q21",
    section: "Самоосъзнатост",
    text: "Имам ясно разбиране за емоционалните си тригери и модели.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q22",
    section: "Самоосъзнатост",
    text: "Преди колко приключи последната ти значима връзка?",
    type: "choice",
    options: [
      { label: "В момента сам/а, 2+ години", value: "long" },
      { label: "6 месеца до 2 години", value: "medium" },
      { label: "По-малко от 6 месеца", value: "recent" },
      { label: "Никога не съм имал/а дългосрочна връзка", value: "never" },
    ],
  },
  {
    id: "q23",
    section: "Самоосъзнатост",
    text: "Поемам отговорност за ролята си в миналите трудности във връзките.",
    type: "scale",
    min: 1,
    max: 5,
    minLabel: "Изобщо не",
    maxLabel: "Напълно",
  },
  {
    id: "q24",
    section: "Самоосъзнатост",
    text: "Какво означава за теб 'готовност за връзка'?",
    type: "open",
    placeholder: "Сподели с няколко думи или изречение...",
  },
  {
    id: "q25",
    section: "Самоосъзнатост",
    text: "Как би те описал най-близкият ти приятел като романтичен партньор?",
    type: "open",
    placeholder: "Сподели с няколко думи или изречение...",
  },
];
